/* ============================================================
   Guess the Correlation — tool strings
   One block per language. Keys must match across all six.
   %s in a value is a runtime placeholder (see LLL_CORR_STR usage
   in app.js — tf() substitutes it).
   ============================================================ */
var LLL_CORR_STRINGS = {

  /* ---------------------------------------------------------- 日本語 */
  "ja": {
    brand: "相関を当てよう",
    instruction: "散布図を見て、2つの変数がどれくらい相関しているか当ててください。",
    guessLabel: "あなたの予想",
    checkBtn: "確認",
    nextBtn: "次へ",
    scoreLabel: "スコア",
    streakLabel: "連続",
    bestLabel: "最高",
    roundLabel: "ラウンド",
    actual: "実際の値",
    showLine: "回帰直線",
    yourGuess: "あなたの予想",
    offBy: "ズレ",

    diffLabel: "難易度", diffEasy: "やさしい", diffNormal: "ふつう", diffHard: "むずかしい",
    diffEasyD: "はっきりした相関",
    diffNormalD: "いろいろな相関",
    diffHardD: "紛らわしい相関・点が少ない",

    modeLabel: "モード", modePractice: "練習", modeChallenge: "チャレンジ",
    modeDaily: "デイリー", modeReverse: "リバース",

    challengeTitle: "60秒チャレンジ",
    challengeSub: "制限時間内に何問こたえられるかな？",
    startChallenge: "スタート",
    timeLeft: "のこり", seconds: "秒",
    challengeOver: "時間切れ！",
    answered: "こたえた数",
    finalScore: "スコア",
    tryAgainBtn: "もう一度",
    backToPractice: "練習にもどる",

    dailyD: "世界共通、毎日おなじ5問",
    dailyTitle: "デイリーチャレンジ",
    dailySub: "今日の日付から作られた5問。世界中の全員が、まったく同じ5問に挑みます。",
    dailyStart: "今日の5問に挑戦",
    dailyOver: "デイリー完了",
    dailyShare: "結果をシェア",
    dailyCopied: "コピーしました",
    dailyPlayed: "今日はもう挑戦しました。また明日、新しい5問が待っています。",
    dailyShareTitle: "相関を当てよう",
    avgMiss: "平均のズレ",

    reverseD: "数値を読んで、散布図をえらぶ",
    revQ: "この相関の散布図はどれ？",
    revCorrect: "正解！",
    revWrong: "残念、はずれ",
    revReveal: "それぞれの実際の r を表示しました。",

    trapTag: "ひっかけ問題",
    trapCurve: "本当の形は直線ではなく、きれいな曲線です。",
    trapCluster: "2つの離れた集団があるだけ。それぞれの中には傾向がありません。相関は「集団の位置」から生まれています。",
    trapLever: "遠くにある1点だけで、この相関が生まれています。",
    trapWhy: "r は関係の「直線的な部分」しか測りません。r が高くても直線とは限らない——必ず散布図を見ましょう。",

    calibTitle: "あなたのクセ",
    calibEmpty: "5問プレイすると、あなたのクセがここに表示されます。",
    calibRounds: "問題数",
    calibMae: "平均のズレ",
    calibUnder: "強い相関を、平均 %s ほど低く見積もる傾向があります。",
    calibOver: "強い相関を、平均 %s ほど高く見積もる傾向があります。",
    calibBalanced: "強い相関の見積もりは、よくバランスが取れています。",
    calibUnderEnd: "低く見る", calibOverEnd: "高く見る",
    calibReset: "記録をリセット",
    calibNote: "多くの人は |r| を低く見積もります。ゆるく傾いて見える散布図は、思ったより相関が強いことが多いのです。このパネルは、あなたにもそのクセがあるかを記録します。強い相関（|r| ≥ 0.5）の問題だけを対象にしています。",

    readTitle: "散布図の読み方",
    readIntro: "散布図は点で2つの値の関係を表します。点が一直線に近いほど相関は強くなります。",
    exStrongPos: "強い正：右上がりに並ぶ",
    exNone: "相関なし：バラバラ",
    exStrongNeg: "強い負：右下がりに並ぶ",
    readTip: "コツ：点全体の「かたち」を見ましょう。細長い線なら強い相関、丸い雲ならほとんど相関なしです。",

    vClose: "ぴったり！", vGood: "おしい！", vOk: "まあまあ", vFar: "今回は外れ",
    vsp: "非常に強い正の相関", sp: "強い正の相関", mp: "中程度の正の相関", wp: "弱い正の相関",
    none: "ほとんど相関なし",
    wn: "弱い負の相関", mn: "中程度の負の相関", sn: "強い負の相関", vsn: "非常に強い負の相関",
    descPos: "一方が増えると、もう一方も増える傾向があります。",
    descNeg: "一方が増えると、もう一方は減る傾向があります。",
    descNone: "2つの変数の間に直線的な関係はほとんどありません。",

    guideTitle: "相関の強さ",
    guideText: "相関係数 r は −1 から +1 の値をとります。0 に近いほど関係が弱く、±1 に近いほど強くなります。",
    gNeg: "強い負", gZero: "なし", gPos: "強い正",
    whatTitle: "相関とは？",
    whatText: "相関は、2つの変数がどれくらい一緒に変化するかを表します。正の相関では両方が同じ方向に動き、負の相関では反対方向に動きます。",
    causeTitle: "相関 ≠ 因果",
    causeText: "2つの変数が相関していても、一方が他方を引き起こすとは限りません。偶然や、隠れた第3の要因による場合もあります。",
    footNote: "LLLシリーズOSSの一つ — 無料・オープンソース。Live Laugh Love が開発しています。",
    viewGithub: "GitHub で見る",

    /* ---- typed guess input ---- */
    guessAria: "r の予想（−1〜1）。数値を入力するか、スライダーを使ってください。",
    signAria: "符号を反転",
    enterHint: "数値を入力して Enter で確認。矢印キーで 0.01 ずつ調整できます。",

    /* ---- pages: nav, tutorial, learn ---- */
    navPlay: "プレイ",
    navTutorial: "チュートリアル",
    navLearn: "学ぶ",
    newHereLink: "チュートリアルを見る",
    newHereText: "— 5ステップ、約2分。",
    ctaLearnT: "相関のしくみ",
    ctaLearnB: "散布図の読み方、強さの目安、そして r にわからないこと。",
    ctaTutT: "チュートリアルを見る",
    ctaTutB: "5ステップ、手を動かして約2分。",
    ctaPlayT: "プレイ",
    ctaPlayB: "実際にためして、どこまで近づけるか。",
    trapLink: "なぜこうなる？ →",
    tutTitle: "チュートリアル",
    tutLede: "短い5ステップ。終わるころには、この数字の意味がわかります。",
    tutPrev: "もどる",
    tutNext: "つぎへ",
    tutDone: "プレイをはじめる",
    tutStep: "ステップ %s / %s",
    t1Title: "1つの点は、2回はかった1人ぶん",
    t1Body: "14人の学生です。勉強した時間が左右の位置、取った点数が高さになります。どれかの点をタップしてみてください。",
    t1Tap: "点をタップすると読めます",
    t1Read: "勉強 %s 時間 → %s 点",
    t1XLabel: "勉強した時間",
    t1YLabel: "点数",
    t2Title: "r は、点の集まり全体をあらわす1つの数字",
    t2Body: "同じ44個の点を並べかえているだけです。スライダーを動かして、r の値がどんな形になるか見てみましょう。",
    t3Title: "強さは「傾き」ではなく「まとまり」",
    t3Body: "どちらも同じ直線にそっています。ちがうのは、点がどれだけ直線に寄りそっているかだけ。それこそが r の測っているものです。",
    t3Tight: "まとまっている",
    t3Loose: "ばらついている",
    t3Punch: "同じ直線でも、ばらつきがちがう。つまり、傾きが急でも相関が強いとはかぎりません。",
    t4Title: "r は直線しか見ていない",
    t4Body: "3つとも r ≒ +0.8。しっかりした直線の関係と同じ値です。でも、どれも直線ではありません。",
    tabCurve: "曲線",
    tabLever: "外れ値",
    tabCluster: "2つの集団",
    t5Title: "やってみましょう",
    t5Body: "本番と同じ問題を1問。予想までスライダーを動かして「確認」を押すと、実際の値がスライダーに印されて、ズレが見えます。",
    t5CtaT: "本番をプレイ",
    t5CtaB: "練習、60秒チャレンジ、今日のデイリー。",
    learnTitle: "相関のしくみ",
    learnLede: "このゲームで試されることを、ぜんぶここに。",
    bandsLede: "それぞれの強さの実例です。くらべる基準にしてください。",
    notTitle: "r にわからないこと",
    notLede: "r が高いだけでは、たいしたことは言えません。次の4つはどれも r ≒ +0.8 ですが、理由はまったくちがいます。",
    notTip: "教訓：かならず散布図を見ること。r は要約であり、要約はかならず何かを捨てています。",
    notHonestT: "くらべるための、正直な例",
    notHonestB: "ふつうのばらつきをもつ、直線的な関係。r = +0.8 とは本来こういう形です。下の3つはそうではありません。",
    notLinearT: "関係が直線だとはかぎらない",
    notOutlierT: "たった1つの外れ値に耐えられない",
    notClusterT: "傾向ではなく、集団のちがいから生まれることがある",
    causeCoincT: "ただの偶然かもしれない",
    causeCoincB: "たくさんの組み合わせを見れば、まったくの偶然できれいに並ぶものが必ず出てきます。探すほど見つかります。",
    causeConfT: "第3の要因が両方を動かしているかもしれない",
    causeConfB: "アイスの売上と水の事故は一緒に増えます。どちらかが原因なのではなく、暑さが両方を引き起こしています。",
    causeRevT: "原因と結果が逆かもしれない",
    causeRevB: "体力のある人ほどよく運動します。運動したから体力がついたのか、体力があるから運動が苦にならないのか。相関だけでは決められません。",

    /* ---- CSV upload ---- */
    uploadTitle: "自分のデータで試す",
    uploadLede: "2列の数値からなる CSV をアップロードしてください。1列目が x、2列目が y として扱われ、散布図と r を表示します。",
    uploadBtn: "CSV ファイルを選ぶ",
    uploadIdle: "ファイル未読み込み。",
    uploadReading: "%s を読み込み中…",
    uploadOk: "%s — %s 個の点を表示しました。",
    uploadSkipped: "%s 行は数値でなかったためスキップしました。",
    uploadPoints: "%s 点",
    uploadTooFew: "相関を計算するには、数値の行が少なくとも 3 つ必要です。",
    uploadTooBig: "ファイルが 5 MB を超えています。もう少し小さいものを試してください。",
    uploadParseErr: "CSV として読み取れませんでした。",
    uploadReadErr: "ファイルを読み込めませんでした。",

    /* ---- drag-and-drop upload ---- */
    dropzoneAria: "ここに CSV ファイルをドロップ、または Enter でファイルを選択",
    dropzoneDrop: "ここに CSV ファイルをドロップ",
    dropzoneOr: "またはクリックして選択",
    uploadNotCsv: "CSV ファイルではないようです。",

    /* ---- advanced metrics ---- */
    metricPearson: "ピアソン r",
    metricSpearman: "スピアマン ρ",
    metricRSq: "決定係数 R²",
    metricPValue: "p値",
    metricSig: "有意",
    metricNotSig: "有意でない",
    metricDivergeHint: "ピアソンとスピアマンの値が大きくずれています。ピアソンは直線の関係しか見ませんが、スピアマンは増加・減少が一貫していればどんな関係でも捉えます。このズレは、実際の関係が直線ではないことを示している場合が多いです — 上の散布図を見てみましょう。"
  },

  /* ---------------------------------------------------------- English */
  "en": {
    brand: "Guess the Correlation",
    instruction: "Look at the scatter plot. How correlated are the two variables?",
    guessLabel: "Your guess",
    checkBtn: "Check",
    nextBtn: "Next",
    scoreLabel: "Score",
    streakLabel: "Streak",
    bestLabel: "Best",
    roundLabel: "Round",
    actual: "Actual",
    showLine: "Trend line",
    yourGuess: "Your guess",
    offBy: "off by",

    diffLabel: "Difficulty", diffEasy: "Easy", diffNormal: "Normal", diffHard: "Hard",
    diffEasyD: "Clear-cut correlations",
    diffNormalD: "A mix of correlations",
    diffHardD: "Tricky ones, fewer points",

    modeLabel: "Mode", modePractice: "Practice", modeChallenge: "Challenge",
    modeDaily: "Daily", modeReverse: "Reverse",

    challengeTitle: "60-second challenge",
    challengeSub: "How many can you get before time runs out?",
    startChallenge: "Start",
    timeLeft: "Time", seconds: "s",
    challengeOver: "Time\u2019s up!",
    answered: "Answered",
    finalScore: "Score",
    tryAgainBtn: "Try again",
    backToPractice: "Back to practice",

    dailyD: "The same five plots for everyone, every day",
    dailyTitle: "Daily challenge",
    dailySub: "Five plots, seeded from today\u2019s date. Everyone in the world gets exactly the same five.",
    dailyStart: "Play today\u2019s five",
    dailyOver: "Daily complete",
    dailyShare: "Share result",
    dailyCopied: "Copied to clipboard",
    dailyPlayed: "You\u2019ve already played today. Come back tomorrow for five new plots.",
    dailyShareTitle: "Guess the Correlation",
    avgMiss: "Avg. miss",

    reverseD: "Read the number, find the plot",
    revQ: "Which plot has this correlation?",
    revCorrect: "Correct!",
    revWrong: "Not this time",
    revReveal: "The real r for each plot is shown above.",

    trapTag: "Trap round",
    trapCurve: "The real pattern is a clean curve, not a line.",
    trapCluster: "Two separate clusters, neither with any internal trend. The correlation comes from where the groups sit, not from a relationship inside them.",
    trapLever: "One far-out point creates the entire correlation.",
    trapWhy: "r only measures the straight-line part of a relationship. A high r never proves the relationship is a line \u2014 always look at the plot.",

    calibTitle: "Your calibration",
    calibEmpty: "Play five rounds and your personal bias will show up here.",
    calibRounds: "Rounds",
    calibMae: "Average miss",
    calibUnder: "You tend to underestimate strong correlations by %s.",
    calibOver: "You tend to overestimate strong correlations by %s.",
    calibBalanced: "Your read on strong correlations is well balanced.",
    calibUnderEnd: "underestimate", calibOverEnd: "overestimate",
    calibReset: "Reset stats",
    calibNote: "Most people underestimate |r|: a plot that looks only mildly tilted is usually more correlated than it feels. This panel tracks whether you do it too. It counts only strong rounds (|r| \u2265 0.5).",

    readTitle: "How to read a scatter plot",
    readIntro: "A scatter plot shows the relationship between two values as dots. The closer the dots come to a straight line, the stronger the correlation.",
    exStrongPos: "Strong positive: dots rise to the right",
    exNone: "No correlation: dots scattered",
    exStrongNeg: "Strong negative: dots fall to the right",
    readTip: "Tip: look at the overall shape. A long thin line means strong correlation; a round cloud means little or none.",

    vClose: "Spot on!", vGood: "Close!", vOk: "Not bad", vFar: "Off this time",
    vsp: "very strong positive", sp: "strong positive", mp: "moderate positive", wp: "weak positive",
    none: "little to no correlation",
    wn: "weak negative", mn: "moderate negative", sn: "strong negative", vsn: "very strong negative",
    descPos: "As one value goes up, the other tends to go up too.",
    descNeg: "As one value goes up, the other tends to go down.",
    descNone: "There\u2019s little to no linear relationship between the two.",

    guideTitle: "Correlation strength",
    guideText: "The correlation coefficient r runs from \u22121 to +1. Values near 0 mean a weak relationship; values near \u00b11 mean a strong one.",
    gNeg: "strong \u2212", gZero: "none", gPos: "strong +",
    whatTitle: "What is correlation?",
    whatText: "Correlation measures how much two variables change together. A positive correlation means they move the same way; a negative one means they move in opposite directions.",
    causeTitle: "Correlation \u2260 causation",
    causeText: "Even when two variables correlate, one may not cause the other. It could be coincidence, or a hidden third factor driving both.",
    footNote: "Part of the LLL Series OSS \u2014 free and open source, built by Live Laugh Love.",
    viewGithub: "View on GitHub",

    /* ---- typed guess input ---- */
    guessAria: "Your guess for r, from -1 to 1. Type a value or use the slider.",
    signAria: "Flip the sign",
    enterHint: "Type a value and press Enter to check. Arrow keys nudge by 0.01.",

    /* ---- pages: nav, tutorial, learn ---- */
    navPlay: "Play",
    navTutorial: "Tutorial",
    navLearn: "Learn",
    newHereLink: "Take the tutorial",
    newHereText: "— five steps, about two minutes.",
    ctaLearnT: "How correlation works",
    ctaLearnB: "Reading plots, the strength scale, and what r can’t tell you.",
    ctaTutT: "Try the tutorial",
    ctaTutB: "Five steps, hands-on, about two minutes.",
    ctaPlayT: "Play",
    ctaPlayB: "Put it to work and see how close you get.",
    trapLink: "Why r does this →",
    tutTitle: "Tutorial",
    tutLede: "Five short steps. By the end you’ll know what the number means.",
    tutPrev: "Back",
    tutNext: "Next",
    tutDone: "Start playing",
    tutStep: "Step %s of %s",
    t1Title: "Every dot is one thing, measured twice",
    t1Body: "Here are 14 students. How long each one revised sets the left-to-right position. The mark they got sets the height. Tap any dot.",
    t1Tap: "Tap a dot to read it",
    t1Read: "Revised %s hours → scored %s",
    t1XLabel: "hours revised",
    t1YLabel: "mark",
    t2Title: "r is one number for the whole cloud",
    t2Body: "These are the same 44 points every time — only rearranged. Drag the slider and watch what each value of r actually looks like.",
    t3Title: "Strength is tightness, not steepness",
    t3Body: "Both clouds follow the same line. The only thing that changed is how closely the dots hug it — and that is exactly what r measures.",
    t3Tight: "tight",
    t3Loose: "loose",
    t3Punch: "Same line, different spread. So a steeper line does not mean a stronger correlation.",
    t4Title: "r only sees straight lines",
    t4Body: "All three of these score around r = +0.8, the same as a solid straight-line relationship. None of them is a straight line.",
    tabCurve: "Curve",
    tabLever: "Outlier",
    tabCluster: "Clusters",
    t5Title: "Your turn",
    t5Body: "One real round. Drag to your best guess, then check. The true value gets marked on the slider so you can see the gap.",
    t5CtaT: "Play for real",
    t5CtaB: "Practice, a 60-second run, or today’s daily.",
    learnTitle: "How correlation works",
    learnLede: "Everything the game is testing, in one place.",
    bandsLede: "Real plots at each strength, so you have something to compare against.",
    notTitle: "What r can’t tell you",
    notLede: "A high r is not proof of much on its own. All four of these plots score around +0.8, for four completely different reasons.",
    notTip: "The lesson: always look at the plot. r is a summary, and every summary throws something away.",
    notHonestT: "An honest one, for comparison",
    notHonestB: "A straight-line relationship with ordinary scatter. This is what r = +0.8 is supposed to look like — the three below are not.",
    notLinearT: "It doesn’t mean the relationship is a line",
    notOutlierT: "It isn’t safe from a single stray point",
    notClusterT: "It can come from groups, not from a trend",
    causeCoincT: "It might be coincidence",
    causeCoincB: "Compare enough pairs of things and some will line up beautifully by pure chance. The more you look, the more you’ll find.",
    causeConfT: "A third thing might drive both",
    causeConfB: "Ice cream sales and drownings rise together. Neither causes the other — hot weather causes both.",
    causeRevT: "The arrow might point the other way",
    causeRevB: "Fit people exercise more. Does exercise make them fit, or does being fit make exercise appealing? The correlation alone can’t say.",

    /* ---- CSV upload ---- */
    uploadTitle: "Try your own data",
    uploadLede: "Upload a CSV with two numeric columns — the first is x, the second is y. We'll plot it and compute r.",
    uploadBtn: "Choose CSV file",
    uploadIdle: "No file loaded.",
    uploadReading: "Reading %s…",
    uploadOk: "%s — %s points plotted.",
    uploadSkipped: "%s rows skipped (non-numeric).",
    uploadPoints: "%s points",
    uploadTooFew: "Need at least 3 numeric rows to compute a correlation.",
    uploadTooBig: "File is larger than 5 MB. Try a smaller sample.",
    uploadParseErr: "Couldn't parse that as CSV.",
    uploadReadErr: "Couldn't read the file.",

    /* ---- drag-and-drop upload ---- */
    dropzoneAria: "Drop a CSV file here, or press Enter to browse",
    dropzoneDrop: "Drop a CSV file here",
    dropzoneOr: "or click to browse",
    uploadNotCsv: "That doesn't look like a CSV file.",

    /* ---- advanced metrics ---- */
    metricPearson: "Pearson r",
    metricSpearman: "Spearman ρ",
    metricRSq: "R²",
    metricPValue: "p-value",
    metricSig: "significant",
    metricNotSig: "not significant",
    metricDivergeHint: "Pearson and Spearman disagree by a fair amount here. Pearson only sees a straight-line relationship; Spearman sees any relationship that consistently rises or falls. That gap usually means the real pattern isn't a straight line — look at the plot above."
  },

  /* ---------------------------------------------------------- 简体中文 */
  "zh-Hans": {
    brand: "猜相关性",
    instruction: "看看散点图，猜猜这两个变量的相关程度。",
    guessLabel: "你的猜测",
    checkBtn: "检查",
    nextBtn: "下一个",
    scoreLabel: "分数",
    streakLabel: "连胜",
    bestLabel: "最高",
    roundLabel: "回合",
    actual: "实际值",
    showLine: "趋势线",
    yourGuess: "你的猜测",
    offBy: "误差",

    diffLabel: "难度", diffEasy: "简单", diffNormal: "普通", diffHard: "困难",
    diffEasyD: "明显的相关",
    diffNormalD: "各种相关",
    diffHardD: "不易分辨、点更少",

    modeLabel: "模式", modePractice: "练习", modeChallenge: "挑战",
    modeDaily: "每日", modeReverse: "反向",

    challengeTitle: "60秒挑战",
    challengeSub: "限时内能答对多少题？",
    startChallenge: "开始",
    timeLeft: "剩余", seconds: "秒",
    challengeOver: "时间到！",
    answered: "已作答",
    finalScore: "分数",
    tryAgainBtn: "再试一次",
    backToPractice: "回到练习",

    dailyD: "全球同题，每天 5 道",
    dailyTitle: "每日挑战",
    dailySub: "由今天的日期生成的 5 道题。全世界的人拿到的题目完全一样。",
    dailyStart: "开始今天的 5 题",
    dailyOver: "每日挑战完成",
    dailyShare: "分享结果",
    dailyCopied: "已复制",
    dailyPlayed: "今天已经挑战过了。明天再来，会有新的 5 题。",
    dailyShareTitle: "猜相关性",
    avgMiss: "平均误差",

    reverseD: "看数字，选散点图",
    revQ: "哪个散点图是这个相关系数？",
    revCorrect: "答对了！",
    revWrong: "这次不对",
    revReveal: "上方已显示每个图的真实 r。",

    trapTag: "陷阱题",
    trapCurve: "真实的形状是一条曲线，而不是直线。",
    trapCluster: "只是两团分开的点，每一团内部都没有趋势。相关性来自两团的位置，而不是内部的关系。",
    trapLever: "整个相关性都来自那一个远处的点。",
    trapWhy: "r 只衡量关系中「直线」的那一部分。r 高不代表关系是直线——一定要看图。",

    calibTitle: "你的偏差",
    calibEmpty: "玩满 5 题后，这里会显示你的个人偏差。",
    calibRounds: "题数",
    calibMae: "平均误差",
    calibUnder: "你倾向于把强相关低估约 %s。",
    calibOver: "你倾向于把强相关高估约 %s。",
    calibBalanced: "你对强相关的判断相当平衡。",
    calibUnderEnd: "低估", calibOverEnd: "高估",
    calibReset: "重置记录",
    calibNote: "大多数人会低估 |r|：看起来只是稍微倾斜的图，实际相关性往往比感觉更强。这里会记录你是否也这样，只统计强相关（|r| ≥ 0.5）的题目。",

    readTitle: "如何读散点图",
    readIntro: "散点图用点表示两个数值之间的关系。点越接近一条直线，相关性就越强。",
    exStrongPos: "强正相关：点向右上升",
    exNone: "无相关：点很分散",
    exStrongNeg: "强负相关：点向右下降",
    readTip: "小技巧：看整体形状。细长的一条线表示强相关；圆圆的一团表示几乎没有相关。",

    vClose: "完全正确！", vGood: "很接近！", vOk: "还不错", vFar: "这次差了点",
    vsp: "非常强的正相关", sp: "强正相关", mp: "中等正相关", wp: "弱正相关",
    none: "几乎没有相关",
    wn: "弱负相关", mn: "中等负相关", sn: "强负相关", vsn: "非常强的负相关",
    descPos: "一个变量增大时，另一个也倾向于增大。",
    descNeg: "一个变量增大时，另一个倾向于减小。",
    descNone: "两个变量之间几乎没有线性关系。",

    guideTitle: "相关强度",
    guideText: "相关系数 r 的取值范围是 −1 到 +1。越接近 0 关系越弱，越接近 ±1 关系越强。",
    gNeg: "强负", gZero: "无", gPos: "强正",
    whatTitle: "什么是相关？",
    whatText: "相关衡量两个变量一起变化的程度。正相关表示同向变化，负相关表示反向变化。",
    causeTitle: "相关 ≠ 因果",
    causeText: "即使两个变量相关，也不代表一个导致了另一个。可能是巧合，或有隐藏的第三个因素同时影响两者。",
    footNote: "LLL 系列开源软件之一——免费开源，由 Live Laugh Love 开发。",
    viewGithub: "在 GitHub 上查看",

    /* ---- typed guess input ---- */
    guessAria: "你对 r 的猜测（−1 到 1）。可以直接输入数值，也可以拖动滑块。",
    signAria: "切换正负号",
    enterHint: "输入数值后按 Enter 检查。方向键可微调 0.01。",

    /* ---- pages: nav, tutorial, learn ---- */
    navPlay: "开始玩",
    navTutorial: "教程",
    navLearn: "学习",
    newHereLink: "先看教程",
    newHereText: "—— 五步，大约两分钟。",
    ctaLearnT: "相关是怎么回事",
    ctaLearnB: "怎么读散点图、强度对照，以及 r 说不了的事。",
    ctaTutT: "看看教程",
    ctaTutB: "五步，动手操作，大约两分钟。",
    ctaPlayT: "开始玩",
    ctaPlayB: "上手试试，看你能猜多准。",
    trapLink: "为什么会这样？ →",
    tutTitle: "教程",
    tutLede: "五个小步骤。看完你就知道这个数字是什么意思了。",
    tutPrev: "上一步",
    tutNext: "下一步",
    tutDone: "开始玩",
    tutStep: "第 %s 步，共 %s 步",
    t1Title: "每个点，都是同一个对象量了两次",
    t1Body: "这里是 14 名学生。复习了多久决定左右位置，考了多少分决定高低。点一下任意一个点试试。",
    t1Tap: "点一下圆点就能读出来",
    t1Read: "复习 %s 小时 → 得 %s 分",
    t1XLabel: "复习小时数",
    t1YLabel: "分数",
    t2Title: "r 是描述整团点的一个数字",
    t2Body: "每次都是同样的 44 个点，只是重新排列。拖动滑块，看看每个 r 值到底长什么样。",
    t3Title: "强度看的是紧密，不是陡峭",
    t3Body: "两团点都沿着同一条线。唯一的差别是点贴得有多紧——而这正是 r 在衡量的东西。",
    t3Tight: "紧密",
    t3Loose: "松散",
    t3Punch: "同一条线，疏密不同。所以线更陡，并不代表相关更强。",
    t4Title: "r 只看得见直线",
    t4Body: "这三个的 r 都在 +0.8 左右，和一个扎实的直线关系一样。但没有一个是直线。",
    tabCurve: "曲线",
    tabLever: "离群点",
    tabCluster: "两团",
    t5Title: "换你试试",
    t5Body: "一道真题。拖到你的猜测，然后按检查。真实值会标在滑块上，让你看见差距。",
    t5CtaT: "正式开玩",
    t5CtaB: "练习、60 秒挑战，或今天的每日题。",
    learnTitle: "相关是怎么回事",
    learnLede: "这个游戏考的东西，都在这里。",
    bandsLede: "每种强度的真实图例，给你一个比较的基准。",
    notTitle: "r 说不了的事",
    notLede: "光是 r 高，说明不了太多。下面四张图的 r 都在 +0.8 左右，原因却完全不同。",
    notTip: "结论：一定要看图。r 是一个概括，而任何概括都会丢掉一些东西。",
    notHonestT: "先看一个诚实的例子",
    notHonestB: "带着正常散布的直线关系。r = +0.8 本来就该长这样——下面三个都不是。",
    notLinearT: "它不代表关系是一条直线",
    notOutlierT: "它挡不住一个离群点",
    notClusterT: "它可能来自分组，而不是趋势",
    causeCoincT: "可能只是巧合",
    causeCoincB: "对比够多的组合，总会有一些纯属碰巧排得很整齐。找得越多，撞上的越多。",
    causeConfT: "可能有第三个因素同时影响两者",
    causeConfB: "冰淇淋销量和溺水人数一起上升。不是谁导致谁，而是天热同时造成了两者。",
    causeRevT: "因果方向可能是反的",
    causeRevB: "体能好的人运动更多。是运动让他们体能好，还是体能好让运动变得轻松？光看相关无法判断。",

    /* ---- CSV upload ---- */
    uploadTitle: "上传你自己的数据",
    uploadLede: "上传两列数值的 CSV：第一列作为 x，第二列作为 y。我们会画出散点图并计算 r。",
    uploadBtn: "选择 CSV 文件",
    uploadIdle: "尚未加载文件。",
    uploadReading: "正在读取 %s……",
    uploadOk: "%s —— 已绘制 %s 个点。",
    uploadSkipped: "有 %s 行不是数值，已跳过。",
    uploadPoints: "%s 个点",
    uploadTooFew: "至少需要 3 行数值才能计算相关系数。",
    uploadTooBig: "文件超过 5 MB，请换一个更小的样本。",
    uploadParseErr: "无法把这个文件解析为 CSV。",
    uploadReadErr: "无法读取该文件。",

    /* ---- drag-and-drop upload ---- */
    dropzoneAria: "把 CSV 文件拖到这里，或按 Enter 浏览文件",
    dropzoneDrop: "把 CSV 文件拖到这里",
    dropzoneOr: "或点击选择文件",
    uploadNotCsv: "这似乎不是 CSV 文件。",

    /* ---- advanced metrics ---- */
    metricPearson: "皮尔逊 r",
    metricSpearman: "斯皮尔曼 ρ",
    metricRSq: "决定系数 R²",
    metricPValue: "p 值",
    metricSig: "显著",
    metricNotSig: "不显著",
    metricDivergeHint: "皮尔逊和斯皮尔曼的结果差异较大。皮尔逊只能看到直线关系，而斯皮尔曼能捕捉任何持续上升或下降的关系。这种差异通常说明真实的关系并非直线——请看看上面的散点图。"
  },

  /* ---------------------------------------------------------- 繁體中文 */
  "zh-Hant": {
    brand: "猜相關性",
    instruction: "看看散點圖，猜猜這兩個變數的相關程度。",
    guessLabel: "你的猜測",
    checkBtn: "檢查",
    nextBtn: "下一個",
    scoreLabel: "分數",
    streakLabel: "連勝",
    bestLabel: "最高",
    roundLabel: "回合",
    actual: "實際值",
    showLine: "趨勢線",
    yourGuess: "你的猜測",
    offBy: "誤差",

    diffLabel: "難度", diffEasy: "簡單", diffNormal: "普通", diffHard: "困難",
    diffEasyD: "明顯的相關",
    diffNormalD: "各種相關",
    diffHardD: "不易分辨、點更少",

    modeLabel: "模式", modePractice: "練習", modeChallenge: "挑戰",
    modeDaily: "每日", modeReverse: "反向",

    challengeTitle: "60秒挑戰",
    challengeSub: "限時內能答對多少題？",
    startChallenge: "開始",
    timeLeft: "剩餘", seconds: "秒",
    challengeOver: "時間到！",
    answered: "已作答",
    finalScore: "分數",
    tryAgainBtn: "再試一次",
    backToPractice: "回到練習",

    dailyD: "全球同題，每天 5 道",
    dailyTitle: "每日挑戰",
    dailySub: "由今天的日期生成的 5 道題。全世界的人拿到的題目完全一樣。",
    dailyStart: "開始今天的 5 題",
    dailyOver: "每日挑戰完成",
    dailyShare: "分享結果",
    dailyCopied: "已複製",
    dailyPlayed: "今天已經挑戰過了。明天再來，會有新的 5 題。",
    dailyShareTitle: "猜相關性",
    avgMiss: "平均誤差",

    reverseD: "看數字，選散點圖",
    revQ: "哪個散點圖是這個相關係數？",
    revCorrect: "答對了！",
    revWrong: "這次不對",
    revReveal: "上方已顯示每個圖的真實 r。",

    trapTag: "陷阱題",
    trapCurve: "真實的形狀是一條曲線，而不是直線。",
    trapCluster: "只是兩團分開的點，每一團內部都沒有趨勢。相關性來自兩團的位置，而不是內部的關係。",
    trapLever: "整個相關性都來自那一個遠處的點。",
    trapWhy: "r 只衡量關係中「直線」的那一部分。r 高不代表關係是直線——一定要看圖。",

    calibTitle: "你的偏差",
    calibEmpty: "玩滿 5 題後，這裡會顯示你的個人偏差。",
    calibRounds: "題數",
    calibMae: "平均誤差",
    calibUnder: "你傾向於把強相關低估約 %s。",
    calibOver: "你傾向於把強相關高估約 %s。",
    calibBalanced: "你對強相關的判斷相當平衡。",
    calibUnderEnd: "低估", calibOverEnd: "高估",
    calibReset: "重置記錄",
    calibNote: "大多數人會低估 |r|：看起來只是稍微傾斜的圖，實際相關性往往比感覺更強。這裡會記錄你是否也這樣，只統計強相關（|r| ≥ 0.5）的題目。",

    readTitle: "如何讀散點圖",
    readIntro: "散點圖用點表示兩個數值之間的關係。點越接近一條直線，相關性就越強。",
    exStrongPos: "強正相關：點向右上升",
    exNone: "無相關：點很分散",
    exStrongNeg: "強負相關：點向右下降",
    readTip: "小技巧：看整體形狀。細長的一條線表示強相關；圓圓的一團表示幾乎沒有相關。",

    vClose: "完全正確！", vGood: "很接近！", vOk: "還不錯", vFar: "這次差了點",
    vsp: "非常強的正相關", sp: "強正相關", mp: "中等正相關", wp: "弱正相關",
    none: "幾乎沒有相關",
    wn: "弱負相關", mn: "中等負相關", sn: "強負相關", vsn: "非常強的負相關",
    descPos: "一個變數增大時，另一個也傾向於增大。",
    descNeg: "一個變數增大時，另一個傾向於減小。",
    descNone: "兩個變數之間幾乎沒有線性關係。",

    guideTitle: "相關強度",
    guideText: "相關係數 r 的範圍是 −1 到 +1。越接近 0 關係越弱，越接近 ±1 關係越強。",
    gNeg: "強負", gZero: "無", gPos: "強正",
    whatTitle: "什麼是相關？",
    whatText: "相關衡量兩個變數一起變化的程度。正相關表示同向變化，負相關表示反向變化。",
    causeTitle: "相關 ≠ 因果",
    causeText: "即使兩個變數相關，也不代表一個導致了另一個。可能是巧合，或有隱藏的第三個因素同時影響兩者。",
    footNote: "LLL 系列開源軟體之一——免費開源，由 Live Laugh Love 開發。",
    viewGithub: "在 GitHub 上查看",

    /* ---- typed guess input ---- */
    guessAria: "你對 r 的猜測（−1 到 1）。可以直接輸入數值，也可以拖動滑桿。",
    signAria: "切換正負號",
    enterHint: "輸入數值後按 Enter 檢查。方向鍵可微調 0.01。",

    /* ---- pages: nav, tutorial, learn ---- */
    navPlay: "開始玩",
    navTutorial: "教學",
    navLearn: "學習",
    newHereLink: "先看教學",
    newHereText: "—— 五步，大約兩分鐘。",
    ctaLearnT: "相關是怎麼回事",
    ctaLearnB: "怎麼讀散點圖、強度對照，以及 r 說不了的事。",
    ctaTutT: "看看教學",
    ctaTutB: "五步，動手操作，大約兩分鐘。",
    ctaPlayT: "開始玩",
    ctaPlayB: "上手試試，看你能猜多準。",
    trapLink: "為什麼會這樣？ →",
    tutTitle: "教學",
    tutLede: "五個小步驟。看完你就知道這個數字是什麼意思了。",
    tutPrev: "上一步",
    tutNext: "下一步",
    tutDone: "開始玩",
    tutStep: "第 %s 步，共 %s 步",
    t1Title: "每個點，都是同一個對象量了兩次",
    t1Body: "這裡是 14 名學生。複習了多久決定左右位置，考了多少分決定高低。點一下任意一個點試試。",
    t1Tap: "點一下圓點就能讀出來",
    t1Read: "複習 %s 小時 → 得 %s 分",
    t1XLabel: "複習小時數",
    t1YLabel: "分數",
    t2Title: "r 是描述整團點的一個數字",
    t2Body: "每次都是同樣的 44 個點，只是重新排列。拖動滑桿，看看每個 r 值到底長什麼樣。",
    t3Title: "強度看的是緊密，不是陡峭",
    t3Body: "兩團點都沿著同一條線。唯一的差別是點貼得有多緊——而這正是 r 在衡量的東西。",
    t3Tight: "緊密",
    t3Loose: "鬆散",
    t3Punch: "同一條線，疏密不同。所以線更陡，並不代表相關更強。",
    t4Title: "r 只看得見直線",
    t4Body: "這三個的 r 都在 +0.8 左右，和一個扎實的直線關係一樣。但沒有一個是直線。",
    tabCurve: "曲線",
    tabLever: "離群點",
    tabCluster: "兩團",
    t5Title: "換你試試",
    t5Body: "一道真題。拖到你的猜測，然後按檢查。真實值會標在滑桿上，讓你看見差距。",
    t5CtaT: "正式開玩",
    t5CtaB: "練習、60 秒挑戰，或今天的每日題。",
    learnTitle: "相關是怎麼回事",
    learnLede: "這個遊戲考的東西，都在這裡。",
    bandsLede: "每種強度的真實圖例，給你一個比較的基準。",
    notTitle: "r 說不了的事",
    notLede: "光是 r 高，說明不了太多。下面四張圖的 r 都在 +0.8 左右，原因卻完全不同。",
    notTip: "結論：一定要看圖。r 是一個概括，而任何概括都會丟掉一些東西。",
    notHonestT: "先看一個誠實的例子",
    notHonestB: "帶著正常散布的直線關係。r = +0.8 本來就該長這樣——下面三個都不是。",
    notLinearT: "它不代表關係是一條直線",
    notOutlierT: "它擋不住一個離群點",
    notClusterT: "它可能來自分組，而不是趨勢",
    causeCoincT: "可能只是巧合",
    causeCoincB: "對比夠多的組合，總會有一些純屬碰巧排得很整齊。找得越多，撞上的越多。",
    causeConfT: "可能有第三個因素同時影響兩者",
    causeConfB: "冰淇淋銷量和溺水人數一起上升。不是誰導致誰，而是天熱同時造成了兩者。",
    causeRevT: "因果方向可能是反的",
    causeRevB: "體能好的人運動更多。是運動讓他們體能好，還是體能好讓運動變得輕鬆？光看相關無法判斷。",

    /* ---- CSV upload ---- */
    uploadTitle: "上傳你自己的資料",
    uploadLede: "上傳兩欄數值的 CSV：第一欄作為 x，第二欄作為 y。我們會畫出散點圖並計算 r。",
    uploadBtn: "選擇 CSV 檔案",
    uploadIdle: "尚未載入檔案。",
    uploadReading: "正在讀取 %s……",
    uploadOk: "%s —— 已繪製 %s 個點。",
    uploadSkipped: "有 %s 列不是數值，已略過。",
    uploadPoints: "%s 個點",
    uploadTooFew: "至少需要 3 列數值才能計算相關係數。",
    uploadTooBig: "檔案超過 5 MB，請換一個更小的樣本。",
    uploadParseErr: "無法把這個檔案解析為 CSV。",
    uploadReadErr: "無法讀取該檔案。",

    /* ---- drag-and-drop upload ---- */
    dropzoneAria: "把 CSV 檔案拖到這裡，或按 Enter 瀏覽檔案",
    dropzoneDrop: "把 CSV 檔案拖到這裡",
    dropzoneOr: "或點擊選擇檔案",
    uploadNotCsv: "這似乎不是 CSV 檔案。",

    /* ---- advanced metrics ---- */
    metricPearson: "皮爾遜 r",
    metricSpearman: "斯皮爾曼 ρ",
    metricRSq: "決定係數 R²",
    metricPValue: "p 值",
    metricSig: "顯著",
    metricNotSig: "不顯著",
    metricDivergeHint: "皮爾遜和斯皮爾曼的結果差異較大。皮爾遜只能看到直線關係，而斯皮爾曼能捕捉任何持續上升或下降的關係。這種差異通常說明真實的關係並非直線——請看看上面的散點圖。"
  },

  /* ---------------------------------------------------------- 한국어 */
  "ko": {
    brand: "상관관계 맞히기",
    instruction: "산점도를 보고 두 변수가 얼마나 상관되어 있는지 맞혀 보세요.",
    guessLabel: "당신의 예측",
    checkBtn: "확인",
    nextBtn: "다음",
    scoreLabel: "점수",
    streakLabel: "연속",
    bestLabel: "최고",
    roundLabel: "라운드",
    actual: "실제 값",
    showLine: "추세선",
    yourGuess: "나의 예측",
    offBy: "오차",

    diffLabel: "난이도", diffEasy: "쉬움", diffNormal: "보통", diffHard: "어려움",
    diffEasyD: "뚜렷한 상관",
    diffNormalD: "다양한 상관",
    diffHardD: "헷갈리는 상관, 점이 적음",

    modeLabel: "모드", modePractice: "연습", modeChallenge: "챌린지",
    modeDaily: "데일리", modeReverse: "리버스",

    challengeTitle: "60초 챌린지",
    challengeSub: "시간 안에 몇 개나 맞힐 수 있나요?",
    startChallenge: "시작",
    timeLeft: "남은 시간", seconds: "초",
    challengeOver: "시간 종료!",
    answered: "응답 수",
    finalScore: "점수",
    tryAgainBtn: "다시 하기",
    backToPractice: "연습으로",

    dailyD: "매일, 전 세계 같은 5문제",
    dailyTitle: "데일리 챌린지",
    dailySub: "오늘 날짜로 생성한 5문제. 전 세계 모두가 똑같은 5문제를 풉니다.",
    dailyStart: "오늘의 5문제 시작",
    dailyOver: "데일리 완료",
    dailyShare: "결과 공유",
    dailyCopied: "복사했어요",
    dailyPlayed: "오늘은 이미 플레이했어요. 내일 새로운 5문제로 만나요.",
    dailyShareTitle: "상관관계 맞히기",
    avgMiss: "평균 오차",

    reverseD: "숫자를 읽고 그래프 고르기",
    revQ: "이 상관계수를 가진 산점도는 어느 것일까요?",
    revCorrect: "정답!",
    revWrong: "이번엔 아니에요",
    revReveal: "각 그래프의 실제 r을 위에 표시했어요.",

    trapTag: "함정 라운드",
    trapCurve: "실제 모양은 직선이 아니라 깔끔한 곡선입니다.",
    trapCluster: "떨어져 있는 두 무리일 뿐, 각 무리 안에는 아무 추세도 없습니다. 상관은 무리의 위치에서 나온 것입니다.",
    trapLever: "멀리 떨어진 점 하나가 상관 전체를 만들어 냅니다.",
    trapWhy: "r은 관계의 직선 부분만 측정합니다. r이 높아도 직선이라는 뜻은 아니에요 \u2014 항상 그래프를 보세요.",

    calibTitle: "나의 편향",
    calibEmpty: "5라운드를 플레이하면 여기에 나의 편향이 나타납니다.",
    calibRounds: "라운드",
    calibMae: "평균 오차",
    calibUnder: "강한 상관을 평균 %s 만큼 낮게 보는 경향이 있어요.",
    calibOver: "강한 상관을 평균 %s 만큼 높게 보는 경향이 있어요.",
    calibBalanced: "강한 상관에 대한 감각이 잘 균형 잡혀 있어요.",
    calibUnderEnd: "낮게 봄", calibOverEnd: "높게 봄",
    calibReset: "기록 초기화",
    calibNote: "대부분의 사람은 |r|을 낮게 봅니다. 살짝 기울어 보이는 그래프도 실제로는 더 강하게 상관된 경우가 많아요. 이 패널은 강한 상관(|r| ≥ 0.5) 라운드만 집계합니다.",

    readTitle: "산점도 읽는 법",
    readIntro: "산점도는 두 값의 관계를 점으로 나타냅니다. 점들이 직선에 가까울수록 상관이 강합니다.",
    exStrongPos: "강한 양: 점이 오른쪽 위로",
    exNone: "상관 없음: 점이 흩어짐",
    exStrongNeg: "강한 음: 점이 오른쪽 아래로",
    readTip: "팁: 전체 모양을 보세요. 가늘고 긴 선이면 강한 상관, 둥근 구름이면 거의 없음입니다.",

    vClose: "정확해요!", vGood: "아깝네요!", vOk: "나쁘지 않아요", vFar: "이번엔 빗나갔어요",
    vsp: "매우 강한 양의 상관", sp: "강한 양의 상관", mp: "중간 양의 상관", wp: "약한 양의 상관",
    none: "상관관계 거의 없음",
    wn: "약한 음의 상관", mn: "중간 음의 상관", sn: "강한 음의 상관", vsn: "매우 강한 음의 상관",
    descPos: "한 값이 오르면 다른 값도 오르는 경향이 있습니다.",
    descNeg: "한 값이 오르면 다른 값은 내려가는 경향이 있습니다.",
    descNone: "두 변수 사이에 선형 관계가 거의 없습니다.",

    guideTitle: "상관의 강도",
    guideText: "상관계수 r은 −1에서 +1 사이입니다. 0에 가까울수록 관계가 약하고, ±1에 가까울수록 강합니다.",
    gNeg: "강한 −", gZero: "없음", gPos: "강한 +",
    whatTitle: "상관관계란?",
    whatText: "상관관계는 두 변수가 얼마나 함께 변하는지를 나타냅니다. 양의 상관은 같은 방향으로, 음의 상관은 반대 방향으로 움직입니다.",
    causeTitle: "상관관계 ≠ 인과관계",
    causeText: "두 변수가 상관되어 있어도 하나가 다른 하나의 원인이라고 할 수는 없습니다. 우연이거나 숨은 제3의 요인 때문일 수 있습니다.",
    footNote: "LLL 시리즈 OSS의 하나 \u2014 무료 오픈소스, Live Laugh Love 제작.",
    viewGithub: "GitHub에서 보기",

    /* ---- typed guess input ---- */
    guessAria: "r에 대한 예측(−1 ~ 1). 값을 입력하거나 슬라이더를 사용하세요.",
    signAria: "부호 바꾸기",
    enterHint: "값을 입력하고 Enter를 누르면 확인합니다. 화살표 키로 0.01씩 조절할 수 있어요.",

    /* ---- pages: nav, tutorial, learn ---- */
    navPlay: "플레이",
    navTutorial: "튜토리얼",
    navLearn: "배우기",
    newHereLink: "튜토리얼 보기",
    newHereText: "— 5단계, 약 2분.",
    ctaLearnT: "상관관계의 원리",
    ctaLearnB: "산점도 읽는 법, 강도 기준, 그리고 r이 말해주지 못하는 것.",
    ctaTutT: "튜토리얼 보기",
    ctaTutB: "5단계, 직접 해보며 약 2분.",
    ctaPlayT: "플레이",
    ctaPlayB: "실제로 해보고 얼마나 가까운지 확인하세요.",
    trapLink: "왜 이렇게 되나요? →",
    tutTitle: "튜토리얼",
    tutLede: "짧은 5단계. 끝나면 이 숫자가 무슨 뜻인지 알게 됩니다.",
    tutPrev: "이전",
    tutNext: "다음",
    tutDone: "플레이 시작",
    tutStep: "%s / %s 단계",
    t1Title: "점 하나는 두 번 측정한 하나의 대상",
    t1Body: "학생 14명입니다. 공부한 시간이 좌우 위치를, 받은 점수가 높이를 정합니다. 아무 점이나 눌러 보세요.",
    t1Tap: "점을 누르면 읽을 수 있어요",
    t1Read: "%s시간 공부 → %s점",
    t1XLabel: "공부한 시간",
    t1YLabel: "점수",
    t2Title: "r은 점 구름 전체를 나타내는 하나의 숫자",
    t2Body: "매번 똑같은 44개의 점을 재배치할 뿐입니다. 슬라이더를 움직여 각 r 값이 실제로 어떤 모습인지 보세요.",
    t3Title: "강도는 기울기가 아니라 밀집도",
    t3Body: "두 구름 모두 같은 직선을 따릅니다. 다른 것은 점이 그 선에 얼마나 붙어 있는지뿐이고, 그것이 바로 r이 재는 것입니다.",
    t3Tight: "빽빽함",
    t3Loose: "흩어짐",
    t3Punch: "같은 직선, 다른 퍼짐. 그러니 선이 가파르다고 상관이 강한 것은 아닙니다.",
    t4Title: "r은 직선만 봅니다",
    t4Body: "세 그래프 모두 r이 +0.8 정도로, 탄탄한 직선 관계와 같은 값입니다. 하지만 어느 것도 직선이 아닙니다.",
    tabCurve: "곡선",
    tabLever: "이상치",
    tabCluster: "두 무리",
    t5Title: "직접 해보기",
    t5Body: "실전과 같은 한 라운드. 예측까지 슬라이더를 옮기고 확인을 누르면, 실제 값이 슬라이더에 표시되어 차이가 보입니다.",
    t5CtaT: "실전 플레이",
    t5CtaB: "연습, 60초 챌린지, 또는 오늘의 데일리.",
    learnTitle: "상관관계의 원리",
    learnLede: "이 게임이 시험하는 모든 것을 한곳에.",
    bandsLede: "각 강도의 실제 그래프입니다. 비교 기준으로 삼으세요.",
    notTitle: "r이 말해주지 못하는 것",
    notLede: "r이 높다는 것만으로는 알 수 있는 게 많지 않습니다. 아래 네 그래프는 모두 r이 +0.8쯤이지만 이유는 전혀 다릅니다.",
    notTip: "교훈: 반드시 그래프를 보세요. r은 요약이고, 모든 요약은 무언가를 버립니다.",
    notHonestT: "비교를 위한 정직한 예",
    notHonestB: "평범한 산포를 가진 직선 관계입니다. r = +0.8은 원래 이런 모습이어야 합니다. 아래 세 개는 그렇지 않습니다.",
    notLinearT: "관계가 직선이라는 뜻은 아닙니다",
    notOutlierT: "점 하나에 흔들립니다",
    notClusterT: "추세가 아니라 집단 차이에서 나올 수 있습니다",
    causeCoincT: "그저 우연일 수 있습니다",
    causeCoincB: "충분히 많은 조합을 비교하면 순전히 우연으로 잘 맞아떨어지는 것이 반드시 나옵니다. 찾을수록 더 나옵니다.",
    causeConfT: "제3의 요인이 둘 다 움직일 수 있습니다",
    causeConfB: "아이스크림 판매와 익사 사고는 함께 늘어납니다. 서로가 원인이 아니라 더운 날씨가 둘 다 일으킵니다.",
    causeRevT: "인과의 방향이 반대일 수 있습니다",
    causeRevB: "체력이 좋은 사람이 운동을 더 합니다. 운동해서 체력이 좋아진 걸까요, 체력이 좋아서 운동이 편한 걸까요? 상관만으로는 알 수 없습니다.",

    /* ---- CSV upload ---- */
    uploadTitle: "내 데이터로 해보기",
    uploadLede: "숫자 두 열이 있는 CSV를 업로드하세요. 첫 열이 x, 두 번째 열이 y입니다. 산점도와 r을 보여드립니다.",
    uploadBtn: "CSV 파일 선택",
    uploadIdle: "불러온 파일이 없습니다.",
    uploadReading: "%s 읽는 중…",
    uploadOk: "%s — %s개의 점을 그렸습니다.",
    uploadSkipped: "숫자가 아닌 %s개 행을 건너뛰었습니다.",
    uploadPoints: "%s개 점",
    uploadTooFew: "상관계수를 계산하려면 숫자 행이 최소 3개 필요합니다.",
    uploadTooBig: "파일이 5 MB보다 큽니다. 더 작은 샘플로 시도해 보세요.",
    uploadParseErr: "CSV로 해석할 수 없었습니다.",
    uploadReadErr: "파일을 읽지 못했습니다.",

    /* ---- drag-and-drop upload ---- */
    dropzoneAria: "여기에 CSV 파일을 드롭하거나 Enter를 눌러 찾아보세요",
    dropzoneDrop: "여기에 CSV 파일을 드롭하세요",
    dropzoneOr: "또는 클릭해서 찾아보기",
    uploadNotCsv: "CSV 파일이 아닌 것 같아요.",

    /* ---- advanced metrics ---- */
    metricPearson: "피어슨 r",
    metricSpearman: "스피어만 ρ",
    metricRSq: "결정계수 R²",
    metricPValue: "p값",
    metricSig: "유의함",
    metricNotSig: "유의하지 않음",
    metricDivergeHint: "피어슨과 스피어만 값이 꽤 차이가 납니다. 피어슨은 직선 관계만 보지만, 스피어만은 꾸준히 증가하거나 감소하는 관계라면 무엇이든 포착합니다. 이런 차이는 대개 실제 관계가 직선이 아니라는 뜻이에요 — 위 그래프를 확인해 보세요."
  },

  /* ---------------------------------------------------------- Bahasa Melayu */
  "ms": {
    brand: "Teka Korelasi",
    instruction: "Lihat plot serakan. Sejauh mana kedua-dua pemboleh ubah berkorelasi?",
    guessLabel: "Tekaan anda",
    checkBtn: "Semak",
    nextBtn: "Seterusnya",
    scoreLabel: "Markah",
    streakLabel: "Berturut",
    bestLabel: "Terbaik",
    roundLabel: "Pusingan",
    actual: "Nilai sebenar",
    showLine: "Garis arah aliran",
    yourGuess: "Tekaan anda",
    offBy: "tersasar",

    diffLabel: "Kesukaran", diffEasy: "Mudah", diffNormal: "Biasa", diffHard: "Sukar",
    diffEasyD: "Korelasi yang jelas",
    diffNormalD: "Pelbagai korelasi",
    diffHardD: "Sukar dibeza, kurang titik",

    modeLabel: "Mod", modePractice: "Latihan", modeChallenge: "Cabaran",
    modeDaily: "Harian", modeReverse: "Songsang",

    challengeTitle: "Cabaran 60 saat",
    challengeSub: "Berapa banyak boleh anda jawab sebelum masa tamat?",
    startChallenge: "Mula",
    timeLeft: "Masa", seconds: "s",
    challengeOver: "Masa tamat!",
    answered: "Dijawab",
    finalScore: "Markah",
    tryAgainBtn: "Cuba lagi",
    backToPractice: "Kembali ke latihan",

    dailyD: "Lima plot yang sama untuk semua, setiap hari",
    dailyTitle: "Cabaran Harian",
    dailySub: "Lima plot yang dijana daripada tarikh hari ini. Semua orang di dunia dapat lima yang sama.",
    dailyStart: "Main lima hari ini",
    dailyOver: "Cabaran harian selesai",
    dailyShare: "Kongsi keputusan",
    dailyCopied: "Disalin",
    dailyPlayed: "Anda sudah bermain hari ini. Kembali esok untuk lima plot baharu.",
    dailyShareTitle: "Teka Korelasi",
    avgMiss: "Purata tersasar",

    reverseD: "Baca nombor, cari plotnya",
    revQ: "Plot yang manakah mempunyai korelasi ini?",
    revCorrect: "Betul!",
    revWrong: "Bukan kali ini",
    revReveal: "Nilai r sebenar bagi setiap plot ditunjukkan di atas.",

    trapTag: "Pusingan perangkap",
    trapCurve: "Bentuk sebenarnya ialah lengkung yang kemas, bukan garis lurus.",
    trapCluster: "Dua kelompok berasingan, tiada arah aliran di dalam mana-mana satu. Korelasi datang daripada kedudukan kumpulan, bukan hubungan di dalamnya.",
    trapLever: "Satu titik yang jauh mencipta keseluruhan korelasi ini.",
    trapWhy: "r hanya mengukur bahagian garis lurus sesuatu hubungan. r yang tinggi tidak membuktikan hubungannya lurus \u2014 sentiasa lihat plotnya.",

    calibTitle: "Kecenderungan anda",
    calibEmpty: "Main lima pusingan dan kecenderungan peribadi anda akan muncul di sini.",
    calibRounds: "Pusingan",
    calibMae: "Purata tersasar",
    calibUnder: "Anda cenderung memandang rendah korelasi kuat sebanyak %s.",
    calibOver: "Anda cenderung memandang tinggi korelasi kuat sebanyak %s.",
    calibBalanced: "Anggaran anda untuk korelasi kuat cukup seimbang.",
    calibUnderEnd: "pandang rendah", calibOverEnd: "pandang tinggi",
    calibReset: "Set semula rekod",
    calibNote: "Kebanyakan orang memandang rendah |r|: plot yang nampak condong sedikit selalunya lebih berkorelasi daripada yang dirasakan. Panel ini menjejaki sama ada anda juga begitu, mengira pusingan kuat sahaja (|r| \u2265 0.5).",

    readTitle: "Cara membaca plot serakan",
    readIntro: "Plot serakan menunjukkan hubungan antara dua nilai sebagai titik. Semakin hampir titik kepada garis lurus, semakin kuat korelasinya.",
    exStrongPos: "Positif kuat: titik naik ke kanan",
    exNone: "Tiada korelasi: titik bertaburan",
    exStrongNeg: "Negatif kuat: titik turun ke kanan",
    readTip: "Petua: lihat bentuk keseluruhan. Garis panjang nipis bermakna korelasi kuat; awan bulat bermakna hampir tiada.",

    vClose: "Tepat sekali!", vGood: "Hampir!", vOk: "Tidak teruk", vFar: "Tersasar kali ini",
    vsp: "positif sangat kuat", sp: "positif kuat", mp: "positif sederhana", wp: "positif lemah",
    none: "hampir tiada korelasi",
    wn: "negatif lemah", mn: "negatif sederhana", sn: "negatif kuat", vsn: "negatif sangat kuat",
    descPos: "Apabila satu nilai naik, satu lagi cenderung naik juga.",
    descNeg: "Apabila satu nilai naik, satu lagi cenderung turun.",
    descNone: "Hampir tiada hubungan linear antara kedua-duanya.",

    guideTitle: "Kekuatan korelasi",
    guideText: "Pekali korelasi r bernilai dari \u22121 hingga +1. Nilai hampir 0 bermaksud hubungan lemah; hampir \u00b11 bermaksud kuat.",
    gNeg: "negatif kuat", gZero: "tiada", gPos: "positif kuat",
    whatTitle: "Apa itu korelasi?",
    whatText: "Korelasi mengukur sejauh mana dua pemboleh ubah berubah bersama. Korelasi positif bergerak sehala; negatif bergerak bertentangan arah.",
    causeTitle: "Korelasi \u2260 sebab",
    causeText: "Walaupun dua pemboleh ubah berkorelasi, satu mungkin tidak menyebabkan yang lain. Mungkin kebetulan, atau faktor ketiga tersembunyi.",
    footNote: "Sebahagian daripada LLL Series OSS \u2014 percuma dan sumber terbuka, dibina oleh Live Laugh Love.",
    viewGithub: "Lihat di GitHub",

    /* ---- typed guess input ---- */
    guessAria: "Tekaan anda untuk r, dari −1 hingga 1. Taip nilai atau guna gelangsar.",
    signAria: "Tukar tanda positif/negatif",
    enterHint: "Taip nilai dan tekan Enter untuk semak. Kekunci anak panah melaraskan 0.01.",

    /* ---- pages: nav, tutorial, learn ---- */
    navPlay: "Main",
    navTutorial: "Tutorial",
    navLearn: "Belajar",
    newHereLink: "Ikuti tutorial",
    newHereText: "— lima langkah, lebih kurang dua minit.",
    ctaLearnT: "Cara korelasi berfungsi",
    ctaLearnB: "Membaca plot, skala kekuatan, dan apa yang r tidak boleh beritahu.",
    ctaTutT: "Cuba tutorial",
    ctaTutB: "Lima langkah, praktikal, lebih kurang dua minit.",
    ctaPlayT: "Main",
    ctaPlayB: "Cuba sendiri dan lihat sedekat mana tekaan anda.",
    trapLink: "Kenapa r begini? →",
    tutTitle: "Tutorial",
    tutLede: "Lima langkah pendek. Selepas ini anda akan faham maksud nombor itu.",
    tutPrev: "Kembali",
    tutNext: "Seterusnya",
    tutDone: "Mula bermain",
    tutStep: "Langkah %s daripada %s",
    t1Title: "Setiap titik ialah satu benda, diukur dua kali",
    t1Body: "Ini 14 orang pelajar. Berapa lama mereka mengulang kaji menentukan kedudukan kiri-kanan. Markah yang diperoleh menentukan ketinggian. Ketik mana-mana titik.",
    t1Tap: "Ketik titik untuk membacanya",
    t1Read: "Ulang kaji %s jam → dapat %s markah",
    t1XLabel: "jam mengulang kaji",
    t1YLabel: "markah",
    t2Title: "r ialah satu nombor untuk keseluruhan awan titik",
    t2Body: "Ini 44 titik yang sama setiap kali — cuma disusun semula. Seret gelangsar dan lihat rupa sebenar setiap nilai r.",
    t3Title: "Kekuatan ialah kerapatan, bukan kecuraman",
    t3Body: "Kedua-dua awan mengikut garis yang sama. Yang berbeza hanyalah serapat mana titik memeluk garis itu — dan itulah yang diukur oleh r.",
    t3Tight: "rapat",
    t3Loose: "renggang",
    t3Punch: "Garis yang sama, taburan berbeza. Jadi garis yang lebih curam tidak bermakna korelasi lebih kuat.",
    t4Title: "r hanya nampak garis lurus",
    t4Body: "Ketiga-tiganya mencatat r lebih kurang +0.8, sama seperti hubungan lurus yang kukuh. Tiada satu pun yang lurus.",
    tabCurve: "Lengkung",
    tabLever: "Titik terpencil",
    tabCluster: "Dua kelompok",
    t5Title: "Giliran anda",
    t5Body: "Satu pusingan sebenar. Seret ke tekaan terbaik anda, kemudian semak. Nilai sebenar akan ditanda pada gelangsar supaya anda nampak jurangnya.",
    t5CtaT: "Main sungguh-sungguh",
    t5CtaB: "Latihan, cabaran 60 saat, atau cabaran harian.",
    learnTitle: "Cara korelasi berfungsi",
    learnLede: "Semua yang diuji oleh permainan ini, di satu tempat.",
    bandsLede: "Plot sebenar bagi setiap kekuatan, sebagai rujukan perbandingan.",
    notTitle: "Apa yang r tidak boleh beritahu",
    notLede: "r yang tinggi sahaja tidak membuktikan banyak perkara. Keempat-empat plot ini mencatat lebih kurang +0.8, atas empat sebab yang berlainan sama sekali.",
    notTip: "Pengajarannya: sentiasa lihat plotnya. r ialah ringkasan, dan setiap ringkasan membuang sesuatu.",
    notHonestT: "Satu yang jujur, untuk perbandingan",
    notHonestB: "Hubungan garis lurus dengan taburan biasa. Beginilah sepatutnya rupa r = +0.8 — tiga di bawah bukan.",
    notLinearT: "Ia tidak bermakna hubungan itu satu garis",
    notOutlierT: "Ia tidak selamat daripada satu titik sesat",
    notClusterT: "Ia boleh datang daripada kumpulan, bukan arah aliran",
    causeCoincT: "Mungkin kebetulan semata-mata",
    causeCoincB: "Bandingkan cukup banyak pasangan, pasti ada yang sejajar dengan cantik secara kebetulan. Lagi banyak dicari, lagi banyak dijumpai.",
    causeConfT: "Faktor ketiga mungkin menggerakkan kedua-duanya",
    causeConfB: "Jualan aiskrim dan kes lemas meningkat bersama. Bukan satu menyebabkan yang lain — cuaca panas menyebabkan kedua-duanya.",
    causeRevT: "Arah sebabnya mungkin terbalik",
    causeRevB: "Orang yang cergas bersenam lebih banyak. Adakah senaman menjadikan mereka cergas, atau kecergasan menjadikan senaman mudah? Korelasi sahaja tidak dapat menjawab.",

    /* ---- CSV upload ---- */
    uploadTitle: "Cuba dengan data anda",
    uploadLede: "Muat naik CSV dua lajur berangka — lajur pertama sebagai x, kedua sebagai y. Kami akan plotkan dan kira r.",
    uploadBtn: "Pilih fail CSV",
    uploadIdle: "Belum ada fail dimuat.",
    uploadReading: "Membaca %s…",
    uploadOk: "%s — %s titik dipaparkan.",
    uploadSkipped: "%s baris bukan angka telah dilangkau.",
    uploadPoints: "%s titik",
    uploadTooFew: "Perlu sekurang-kurangnya 3 baris berangka untuk mengira korelasi.",
    uploadTooBig: "Fail melebihi 5 MB. Cuba sampel yang lebih kecil.",
    uploadParseErr: "Tidak dapat menghurai fail itu sebagai CSV.",
    uploadReadErr: "Tidak dapat membaca fail itu.",

    /* ---- drag-and-drop upload ---- */
    dropzoneAria: "Lepaskan fail CSV di sini, atau tekan Enter untuk semak imbas",
    dropzoneDrop: "Lepaskan fail CSV di sini",
    dropzoneOr: "atau klik untuk semak imbas",
    uploadNotCsv: "Ini nampaknya bukan fail CSV.",

    /* ---- advanced metrics ---- */
    metricPearson: "Pearson r",
    metricSpearman: "Spearman ρ",
    metricRSq: "R²",
    metricPValue: "nilai-p",
    metricSig: "signifikan",
    metricNotSig: "tidak signifikan",
    metricDivergeHint: "Pearson dan Spearman tidak sepadan di sini. Pearson hanya nampak hubungan garis lurus; Spearman menangkap sebarang hubungan yang sentiasa meningkat atau menurun. Jurang ini biasanya bermaksud corak sebenar bukan garis lurus — lihat plot di atas."
  }
};
